pipeline {
    agent {
        label 'devops'
    }
    environment  {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git url:'https://github.com/tarunp2912/testproject.git', branch:'main'
            }
        }
        stage('Sonarqube Analysis ') {
            steps {
                dir('src/') {
                    withSonarQubeEnv('sonar-scanner') {
                        sh ''' $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=test \
                        -Dsonar.projectKey=test '''
                    }
                }
            }
        }
        stage('QualityGate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token' 
                }
            }
        }
        stage('OWASP Scan') {
            steps {
                dir('src/') {
                    dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
                }
            }
        }
        stage('TrivyFScan') {
            steps {
                dir('src/') {
                    sh 'trivy fs . > trivyfs.txt'
                }
            }
        }
        stage("Image Create") {
            steps {
                script {
                    sh 'docker build -t testproject .'

                }
            }
        }
        // stage("ImagePush") {
        //     steps {
        //         script {
        //             withCredentials([usernamePassword(credentialsId: 'docker-repo-creds', usernameVariable: 'docker_user', passwordVariable: 'docker_pass')]) {
        //             sh "docker tag finexo ${env.docker_user}/finexo:${BUILD_NUMBER}"
        //             sh "docker login -u ${env.docker_user} -p ${env.docker_pass}"
        //             sh "docker push ${env.docker_user}/finexo:${BUILD_NUMBER}"
        //             }
        //         }
        //     }
        // }
        // stage("ImageScan") {
        //     steps {
        //     }
        // }
    }
}